name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 09 * * 2'

jobs:
  scheduled:
    environment: scraper
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      env:
        API_KEY: ${{ secrets.API_KEY }}
        PLAN_URL: ${{ secrets.PLAN_URL }}
        COMMISSIONS_URL: ${{ secrets.COMMISSIONS_URL }}
      run: .github/scrape.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
